server:
  error:
    include-stacktrace: on_param

springdoc:
  swagger-ui:
    path: /swagger.html

spring:
  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
          hibernate:
            dialect:
              PostgreSQLDialect:






